class I2C
  def init: (Integer?, Integer?, Integer?, Integer?, Integer?) -> void
  def deinit: () -> void
  def write: (Integer, Array[Integer], bool?, Integer?) -> Integer
  def read: (Integer, Array[Integer], bool?, Integer?) -> Integer
end
