class Rearranger
  @n_rows: Integer
  @n_cols: Integer
  @index_map: Hash[Integer, Array[Integer]]
  def initialize: (Array[IoExpander], Integer) -> void
  def arrange: (Array[Symbol]) -> Array[Symbol]
end

